# Generated by Django 3.2.8 on 2021-10-17 23:23

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=rooms.models.Photo.user_directory_path),
        ),
    ]
